title: Axway Tech Lab
description: Self-paced hands-on labs to discover the product
show_downloads: false
show_repository: false
# owner_name: Axway Tech Labs
# owner_url: https://www.axway.com/events-and-webinars
logo_url: https://avatars.githubusercontent.com/u/5559759
copyright: 2026 Axway
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one